[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[dev]
  framework = "#custom"
  command = "pnpm dev" # Command to start your dev server
  targetPort = 3333 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on

[functions]
  node_bundler = "esbuild"