/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProducts: typeof import('./components/AppProducts.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    BaseLink: typeof import('./components/BaseLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHomePage: typeof import('./components/TheHomePage.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
  }
}
