// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProducts: typeof import('./components/AppProducts.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    BaseLink: typeof import('./components/BaseLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHomePage: typeof import('./components/TheHomePage.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
  }
}
